
@baseUrl = http://localhost:3000

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### AppControllerGetHello
# @name AppControllerExemplo
GET {{baseUrl}}/home/exemplo

### ConceitosManualControler Home
# @name ConceitosManualController
GET {{baseUrl}}/conceitos-manual

### ConceitosAutomaticoController
# @name ConceitosAutomaticoController
GET {{baseUrl}}/conceitos-automatico


### ExemploDeRota
# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo

